// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgX-fgr_wGgt0qnKvq6P_LSRSW-npOoHw',
    appId: '1:16375532651:web:61a5d0c925af0eab00b52e',
    messagingSenderId: '16375532651',
    projectId: 'hi-kod-60e2c',
    authDomain: 'hi-kod-60e2c.firebaseapp.com',
    storageBucket: 'hi-kod-60e2c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLyf3VlPtBq_ono2WiXAa6UJ5_JHFJehA',
    appId: '1:16375532651:android:de7bfc2afaba3a3000b52e',
    messagingSenderId: '16375532651',
    projectId: 'hi-kod-60e2c',
    storageBucket: 'hi-kod-60e2c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCZSB8D4jnRqVunyBQHWqL1DRb5Keyt5U',
    appId: '1:16375532651:ios:788c6a21298f04b900b52e',
    messagingSenderId: '16375532651',
    projectId: 'hi-kod-60e2c',
    storageBucket: 'hi-kod-60e2c.firebasestorage.app',
    iosBundleId: 'com.example.hiKod',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCZSB8D4jnRqVunyBQHWqL1DRb5Keyt5U',
    appId: '1:16375532651:ios:788c6a21298f04b900b52e',
    messagingSenderId: '16375532651',
    projectId: 'hi-kod-60e2c',
    storageBucket: 'hi-kod-60e2c.firebasestorage.app',
    iosBundleId: 'com.example.hiKod',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgX-fgr_wGgt0qnKvq6P_LSRSW-npOoHw',
    appId: '1:16375532651:web:cda3b11e2fdc0d7300b52e',
    messagingSenderId: '16375532651',
    projectId: 'hi-kod-60e2c',
    authDomain: 'hi-kod-60e2c.firebaseapp.com',
    storageBucket: 'hi-kod-60e2c.firebasestorage.app',
  );
}
